import Enumerator from "../modules/enumerator";

export const tool = {
  html: "HTML",
  erb: "HTML/ERB",
  pug: "Pug",
  jade: "Pug",
  haml: "Haml",
  slim: "Slim",
  css: "CSS",
  sass: "SCSS",
  scss: "SCSS",
  less: "Less",
  cucumber: "Cucumber",
  unity: "Unity",
  rails: "Ruby on Rails",
  php: "PHP",
  python: "Python",
  javascript: "Javascript",
  vue: "Vue",
  angular: "Angular",
  react: "React",
  grunt: "GruntJS",
  three: "ThreeJS",
  jQuery: "jQuery",
  json: "JSON",
  miva: "Miva",
  markdown: "Markdown",
  bootstrap: "Bootstrap",
  git: "Git",
  flash: "Adobe Flash",
  illustrator: "Adobe Illustrator",
  photoshop: "Adobe Photoshop",
  indesign: "Adobe Indesign",
  afterEffects: "Adobe After Effects",
  premiere: "Adobe Premiere",
  inkscape: "Inkscape",
  typescript: "TypeScript",
  vuex: "Vuex",
  vueRouter: "Vue Router",
  sizzle: "Sizzle",
  lodash: "Lodash",
  velocity: "Velocity.js",
  canvas: "Canvas",
  sweetAlert: "Sweetalert",
  stellar: "stellarJS",
  animate: "Animate CSS",
  snapSVG: "snapSVG",
  svelte: "Svelte",
  chartJS: "ChartJS",
  wordpress: "Wordpress",
  kotlin: "Kotlin",
  tweenMax: "TweenMax",
  firebase: "Firebase",
  webpack: "Webpack",
  mysql: "MySQL",
  jest: "Jest",
  blender: "Blender",
  maya: "Maya",
  drupal: "Drupal",
  scribus: "Scribus",
  redux: "Redux",
  mongo: "MongoDB",
  gulp: "Gulp",
  svg: "SVG",
  joomla: "Joomla",
  highlight: "Highlight.js",
  freehand: "Freehand",
  sk1: "SK1",
  fireworks: "Fireworks",
  corelDraw: "Corel Draw",
  autocad: "Autocad",
  gimp: "Gimp",
  pencil: "Pencil",
  gmap: "Google Maps",
  axios: "Axios",
  pascal: "Pascal",
  c: "C++",
  vb: "Visual Basic",
  vfoxpro: "Visual FoxPro",
  bash: "Bash",
  linux: "Linux",
  excel: "Microsoft Excel",
  word: "Microsoft Word",
  powerpoint: "Microsoft Powerpoint",
  dreamweaver: "Adobe Dreamweaver",
  as2: "ActionScript 2",
  as3: "ActionScript 3",
  tkinter: "Tkinter",
  konva: "Konva",
  i18n: "vue-i18n",
  webComponents: "Web Components",
};

export const toolR = Object.values(tool);

export const toolEnum = new Enumerator(
  ...Object.keys(tool)
);