export const type = {
  userFlow: "User Flow",
  wireFrame: "Wireframe",
  app: "Application",
  prototype: "Prototype",
  landingPage: "Landing Page",
  motionGraphics: "Motion Graphics",
  animation3D: "3D Animation",
  document: "Documentation",
  module: "Module",
  socialMedia: "Social Media",
  graphicDesign: "Graphic Design",
  group: "Group",
  location: "Location",
};