import { tool } from "../enums/tools";

export const videos = [
  {
    url: "https://miguel-rivas.github.io/zapp/videos/mr-universe.mp4",
    width: 325,
    height: 580,
    title: "MR Universe",
    soundtrack: { artist: "Pantoja", song: "Bebesina" },
    skills: [
      tool.unity,
      tool.blender,
    ],
  },
  {
    url: "https://miguel-rivas.github.io/zapp/videos/avatar.mp4",
    width: 325,
    height: 580,
    title: "Avatar Builder",
    soundtrack: { artist: "Silva e Ivete Sangalo", song: "Pra Vida Inteira" },
    skills: [
      tool.vue,
      tool.konva,
    ],
  },
  {
    url: "https://miguel-rivas.github.io/zapp/videos/flipbook.mp4",
    width: 325,
    height: 580,
    title: "Flipbook",
    soundtrack: { artist: "Laura Pausini", song: "Incancellabile" },
    skills: [
      tool.vue,
      tool.three,
      tool.indesign,
    ],
  },
  {
    url: "https://miguel-rivas.github.io/zapp/videos/cube.mp4",
    width: 325,
    height: 580,
    title: "Color Cube",
    soundtrack: { artist: "Shakira", song: "Antología" },
    skills: [
      tool.vue,
      tool.three,
    ],
  },
  {
    url: "https://miguel-rivas.github.io/zapp/videos/bitmap.mp4",
    width: 325,
    height: 580,
    title: "Bitmap Editor",
    soundtrack: { artist: "Tatsuro Yamashita", song: "Magic Ways" },
    skills: [
      tool.vue,
      tool.konva,
    ],
  },
  {
    url: "https://miguel-rivas.github.io/zapp/videos/map.mp4",
    width: 325,
    height: 580,
    title: "3D Map",
    soundtrack: { artist: "Natalia Lafourcade", song: "Alma Mía" },
    skills: [
      tool.vue,
      tool.konva,
      tool.blender,
      tool.i18n,
    ],
  },
  {
    url: "https://miguel-rivas.github.io/zapp/videos/tetravex.mp4",
    width: 325,
    height: 580,
    title: "Tetravex",
    soundtrack: { artist: "Roberto Carlos", song: "Nega" },
    skills: [
      tool.javascript,
      tool.sizzle,
      tool.scss,
    ],
  },
  {
    url: "https://miguel-rivas.github.io/zapp/videos/gmap.mp4",
    width: 325,
    height: 580,
    title: "Google Map",
    soundtrack: { artist: "Toquinho", song: "Verrà il giorno" },
    skills: [
      tool.vue,
      tool.gmap,
      tool.scss,
    ],
  },
  {
    url: "https://miguel-rivas.github.io/zapp/videos/2022.mp4",
    width: 325,
    height: 580,
    title: "Portfolio 2022",
    soundtrack: { artist: "Surfaces", song: "Come With Me" },
    skills: [
      tool.vue,
      tool.vueRouter,
      tool.vuex,
      tool.i18n,
      tool.svg,
      tool.three,
      tool.blender,
      tool.konva,
      tool.scss,
      tool.pug,
    ],
  },
  {
    url: "https://miguel-rivas.github.io/zapp/videos/2016.mp4",
    width: 325,
    height: 580,
    title: "Portfolio 2016",
    soundtrack: { artist: "Anri", song: "Remember Summer Days" },
    skills: [
      tool.react,
      tool.scss,
    ],
  },
  {
    url: "https://miguel-rivas.github.io/zapp/videos/2014.mp4",
    width: 325,
    height: 580,
    title: "Portfolio 2014",
    soundtrack: { artist: "Anavitória", song: "Preta" },
    skills: [
      tool.svelte,
      tool.scss,
    ],
  },
];