import { tool } from "@/enums/tools";

export const videos = [
  {
    url: "faHv5bk0XRs",
    width: 325,
    height: 580,
    title: "2D Game",
    soundtrack: { artist: "Georgel, Katzu Oso", song: "Casa" },
    skills: [
      tool.phaser,
      tool.inkscape,
    ],
  },
  {
    url: "6uZ5Ct-27xs",
    width: 325,
    height: 580,
    title: "MR Universe",
    soundtrack: { artist: "Pantoja", song: "Bebesina" },
    skills: [
      tool.unity,
      tool.blender,
    ],
  },
  {
    url: "g_EGSXLiLjI",
    width: 325,
    height: 580,
    title: "Flipbook",
    soundtrack: { artist: "Laura Pausini", song: "Incancellabile" },
    skills: [
      tool.vue,
      tool.three,
      tool.indesign,
    ],
  },
  {
    url: "CxEdTFO9NFw",
    width: 325,
    height: 580,
    title: "Portfolio 2014",
    soundtrack: { artist: "Anavitória", song: "Preta" },
    skills: [
      tool.svelte,
      tool.scss,
    ],
  },
  {
    url: "I42Y0NOo9Vw",
    width: 325,
    height: 580,
    title: "Portfolio 2016",
    soundtrack: { artist: "Anri", song: "Remember Summer Days" },
    skills: [
      tool.react,
      tool.scss,
    ],
  },
  {
    url: "XWKzvWazwt8",
    width: 325,
    height: 580,
    title: "Avatar Builder",
    soundtrack: { artist: "Silva e Ivete Sangalo", song: "Pra Vida Inteira" },
    skills: [
      tool.vue,
      tool.konva,
    ],
  },
  {
    url: "WyylhEi-vFE",
    width: 325,
    height: 580,
    title: "3D Map",
    soundtrack: { artist: "Natalia Lafourcade", song: "Alma Mía" },
    skills: [
      tool.vue,
      tool.konva,
      tool.blender,
      tool.i18n,
    ],
  },

  // {
  //   url: "xlOhfLFhq0c",
  //   width: 325,
  //   height: 580,
  //   title: "Color Cube",
  //   soundtrack: { artist: "Shakira", song: "Antología" },
  //   skills: [
  //     tool.vue,
  //     tool.three,
  //   ],
  // },
  // {
  //   url: "2cwJi7k47Bw",
  //   width: 325,
  //   height: 580,
  //   title: "Bitmap Editor",
  //   soundtrack: { artist: "Tatsuro Yamashita", song: "Magic Ways" },
  //   skills: [
  //     tool.vue,
  //     tool.konva,
  //   ],
  // },
  // {
  //   url: "XG95fpbK53M",
  //   width: 325,
  //   height: 580,
  //   title: "Tetravex",
  //   soundtrack: { artist: "Roberto Carlos", song: "Nega" },
  //   skills: [
  //     tool.javascript,
  //     tool.sizzle,
  //     tool.scss,
  //   ],
  // },
  // {
  //   url: "7Am9nTUXNY0",
  //   width: 325,
  //   height: 580,
  //   title: "Google Map",
  //   soundtrack: { artist: "Toquinho", song: "Verrà il giorno" },
  //   skills: [
  //     tool.vue,
  //     tool.gmap,
  //     tool.scss,
  //   ],
  // },
  // {
  //   url: "ss8B1pnSuEk",
  //   width: 325,
  //   height: 580,
  //   title: "Portfolio 2022",
  //   soundtrack: { artist: "Surfaces", song: "Come With Me" },
  //   skills: [
  //     tool.vue,
  //     tool.vueRouter,
  //     tool.vuex,
  //     tool.i18n,
  //     tool.svg,
  //     tool.three,
  //     tool.blender,
  //     tool.konva,
  //     tool.scss,
  //     tool.pug,
  //   ],
  // },
];